### ISSUE TITLE
shutIt reset

### ISSUE THREAD

**Issue by joopvdl** [phdsg/PvC#7] opened 2018-02-14 11:02 UTC
A reset input for shutit would be very useful to me! So when using it in a song, yo can be sure it starts with the default setting.

**Comment by phdsg** [comment] 2018-02-14 11:17
thx for the feedback.
i agree that's a useful feature. and not hard to integrate.
but i'd have to change the panel layout(s) a bit.
may i ask which version you are using?
i'm currently a bit undecided whether i should keep the 4,8,12 ch versions or just do one.

**Comment by joopvdl** [comment] 2018-02-14 11:34
I'm on 0.5.7, I think that's the latest version, right? I like the 8ch because it's quite efficient in space usage. I like to use it to control levels in an ch mixer, so that's very convenient. But there's not much room for a reset input, as it is now, I guess. I haven't seen the 4 and 12 ch versions, I think.

**Comment by joopvdl** [comment] 2018-02-14 13:04
Yes, I think that would be excellent. So you can start with all channels muted or unmuted. Great idea, it's sort of a reset function where you can choose the initial state.

**Comment by phdsg** [comment] 2018-02-14 14:01
ok, done...ish!
![shutit](https://user-images.githubusercontent.com/33329578/36207985-e5d18b5c-1197-11e8-94b7-4c33c2dc8c98.png)

while hacking this together, i came up with another idea, but i'm not sure if it suits your needs...
a menu option to saves whether the module is relaunched in "init" state or in the "last saved" state.
how's that?

**Comment by joopvdl** [comment] 2018-02-14 14:16
you mean when re-opening the patch?

**Comment by phdsg** [comment] 2018-02-14 14:20
yes, that's the idea.
menu choice will be stored in the .vcv file.

**Comment by joopvdl** [comment] 2018-02-14 14:37
it's a great idea. so you can start with open and closed settings. that
said, when you stop and re-start a song (which I do a lot), you cannot use
this function. Because it will only return to the initial state after
re-opening the patch.

**Comment by phdsg** [comment] 2018-02-14 15:00
correct! it was just a "convenience" thing for re-opening a patch.
ok so, i'll leave it at that for now and save the menu thing for later.

can't thank you enough for your input.
it really helps to have feedback from other users.
i had already ditched the 8ch version, but now i'll probably only keep this one and ditch the rest.

**Comment by joopvdl** [comment] 2018-02-14 15:05
I'm the one to say thank you!
If you like some more feedback, please let me know, I'd be more than happy
to help.
Joop

**Comment by phdsg** [comment] 2018-02-14 15:32
just shoot!
all feedback helps.
so far i've received close to none and therefore most of the modules are kind of centered around my way of doing things in rack, while others might use them in a way i never thought of.

and exchange of ideas always leads to new ideas :)
i.e. you mentioned "starting/stopping a lot". i immediately remembered how i used to always hit the space bar in vcv for the first sessions. just out of daw habit.
gave me the idea that maybe i can make the button module have a "bind-to-key" function...

**Comment by joopvdl** [comment] 2018-02-14 16:08
Yes, that would be wonderful! Keep hitting space, too :)  I actually brought that up on the facebook group, a few weeks ago. I believe Andrew said it's not possible, though.
I would really like some expansion of the bernoulli gate idea. Bernoulli switches. Basically the same switch we discussed before, but with a bernoulli-style randomness to it. So the difference between the current bernoulli gate would be that it can actually input and output  a cv or audio, instead of just a pulse. It would need a reset function, too, I guess.

**Comment by phdsg** [comment] 2018-02-14 16:30
funny coincidence that you bring up bernoulli gates.
big fan too, so i made a module (unreleased still) that's basically a tree of 7 bernoulli gates.
saving some space that way.
![coins](https://user-images.githubusercontent.com/33329578/36215021-32159cca-11ab-11e8-81e3-d0267dffa71f.gif)

i know that's not what you were asking for, but your idea is nice too and i'll give it shot.

just to understand correctly, because there's two ways:
signal flow: input -> chance-gate -> output  
chance-gate has a probability filter that depending on the outcome decides if the trigger  
1) changes the state or not  
or  
2) directly sets state MUTE or UNMUTE

**Comment by joopvdl** [comment] 2018-02-14 16:50
That's it. And an input trigger to trigger the probability filter.
And of course it has to have lots of blinking lights :)
Now I'm trying to make sense of your bernoulli tree..

**Comment by phdsg** [comment] 2018-02-14 16:55
its just one bernoulli gate, outputs fed into 2 more, their outputs fed into 4 more.
each individual gate has its own input that overides whats coming from above.

**Comment by joopvdl** [comment] 2018-02-14 17:44
nice!

2018-02-14 17:55 GMT+01:00 phdsg vn chfhn <notifications@github.com>:

**Comment by phdsg** [comment] 2018-02-14 17:59
back to the switch. i prototyped it like this:
4HP, 2 sections
1 - A or B into OUT  
2 - IN into A or B  
each section has:
trigger to flip the current state,
trigger to toss a coin with associated probability knob over cv
triggers to directly set A or B.
with a layout roughly like this:
![chanceswitches](https://user-images.githubusercontent.com/33329578/36219778-c6dab1b2-11b8-11e8-8251-7528e01d10fc.png)

**Comment by joopvdl** [comment] 2018-02-14 18:12
so it's a probability switch, but also usable as a regular switch, right?

**Comment by joopvdl** [comment] 2018-02-14 18:14
Maybe it's better to have two different versions, one AB into out, one in into AB. Because I'm afraid you'll just need half of the device most of the time.

**Comment by phdsg** [comment] 2018-02-14 18:17
yes to the first question!
and you're probably right about that second thing too.
back to the drawing board...

**Comment by joopvdl** [comment] 2018-02-14 19:00
is the red circle that says prob a cv input or a knob?

**Comment by phdsg** [comment] 2018-02-14 19:18
yep, placeholders for probability knob+cv.
upper one would be the knob, then cv, then label.

**Comment by joopvdl** [comment] 2018-02-14 20:13
I'm starting to look forward to this one!

**Comment by phdsg** [comment] 2018-02-14 20:22
okidoke, _InToAorB_ sort of done (except lights):  
![intoaorb](https://user-images.githubusercontent.com/33329578/36225977-baa8fa7a-11cc-11e8-82bd-42b2531c8402.png)

**Comment by joopvdl** [comment] 2018-02-14 20:24
NICE!

2018-02-14 21:22 GMT+01:00 phdsg vn chfhn <notifications@github.com>:

**Comment by phdsg** [comment] 2018-02-14 21:22
ok, committed to master branch.
do you use the binary releases or are you building from source?

**Comment by joopvdl** [comment] 2018-02-14 21:45
have been trying, but no luck so far.
so it's just binaries for now for me.

**Comment by phdsg** [comment] 2018-02-14 21:54
ok, gonna make a beta build then. what platform?

oh and the question from above still remains:
would you like the coin-toss result to
**a)** flip the state _OR_ not  
**or**
**b)** switch to A _OR_ B  
currently i'm using **b**, but if **a** is useful too i can make an option for that.

**Comment by joopvdl** [comment] 2018-02-14 22:15
I'm on windows.
I do not really understand the question. Isn't the state always either A or
B? In that case, I can't see how option would happen.
Anyway I am a bit confused by the four outputs. I thought it would be input
to either A or B. So one input, two outputs. And its brother, with two
inputs, one output.



2018-02-14 22:54 GMT+01:00 phdsg vn chfhn <notifications@github.com>:

**Comment by phdsg** [comment] 2018-02-14 22:44
the difference in short:
a) tosses coin to decide whether to switch outputs. (heads: switch / tails: don't switch)
b) tosses coin to decide which output is on (heads: B(HI) / tails: A(LO) )

the four outputs explained:
i added gate outs that are high when its output is on.  

[PvC-0.5.8-win.zip](https://github.com/phdsg/PvC/files/1725883/PvC-0.5.8-win.zip)

gonna work on AorBtoOut tomorrow.

**Comment by joopvdl** [comment] 2018-02-14 22:57
Looking good!
Btw nice blank panel :)
good night, looking forward to what tomorrow will bring.

Joop

2018-02-14 23:44 GMT+01:00 phdsg vn chfhn <notifications@github.com>:

**Comment by phdsg** [comment] 2018-02-14 23:02
damn, i just noticed a bug:
cv input for the prob is somehow not working as intended.
gonna fix that tomorrow too.

**Comment by phdsg** [comment] 2018-02-14 23:30
closing this issue.
went a little bit off topic.
feel free to open new ones whenever something comes up.

**Closed by phdsg** 2018-02-14 23:30 UTC
Labels: Feature Request
